name: Build Kernel A32 4G
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Install 32-bit libs and tools
         run: |
      sudo dpkg --add-architecture i386
      sudo apt-get update
      sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev libncurses5 libc6:i386 libncurses5:i386 libstdc++6:i386

      - name: Build
        run: |
          # Define absolute paths to toolchains
          export TOOLCHAIN64=$(pwd)/gcc64/bin
          export TOOLCHAIN32=$(pwd)/gcc32/bin
          export PATH=$TOOLCHAIN64:$TOOLCHAIN32:$PATH
          
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-android-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          
          make O=out clean
          make O=out a32_defconfig
          
          # Force the build to use the downloaded GCC and ignore stack protector error
          make O=out -j$(nproc --all) \
            CC=$TOOLCHAIN64/aarch64-linux-android-gcc \
            LD=$TOOLCHAIN64/aarch64-linux-android-ld \
            KCFLAGS="-w -fno-stack-protector"
